### ISSUE TITLE
cant run single player

### ISSUE THREAD

**Issue by kristosb** [dr-vortex/blankstorm#1]
Tried on win and mac chrome. There is an error when starting single player game:

Uncaught TypeError: Cannot read properties of undefined (reading 'debug_tooltips')
    at Object.lab (blankstorm.drvortex.dev/:1518:440)
    at Object.update (blankstorm.drvortex.dev/:1540:22)
    at IDBRequest.db.transaction.objectStore.get.onsuccess (blankstorm.drvortex.dev/:1348:6)
(index):1451 Loaded mods: 
(index):1379 Do not paste any code someone gave you, as they may be trying to steal your information
onresize @ (index):1379
DevTools failed to load source map: Could not load content for https://blankstorm.drvortex.dev/libraries/babylon/babylon.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://blankstorm.drvortex.dev/libraries/socket.io/socket.io.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
5.2.0.js:1 Uncaught (in promise) RuntimeError: Unable to load from model/corvette.gltf: Cannot read properties of undefined (reading 'asset')
    at t [as constructor] (5.2.0.js:1:206479)
    at new t (5.2.0.js:1:206827)
    at h (5.2.0.js:1:2108099)
    at 5.2.0.js:1:2108629

**Comment by dr-vortex** [comment]
Issue was caused by using an old babylon loaders version. See [this](https://forum.babylonjs.com/t/29800/5) thread for more info.
